name: desafioApi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Install Newman Reporter HTML
      run: npm install -g newman-reporter-html

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run Postman Collection
      run: newman run DesafioApiViaCep.postman_collection.json --reporters cli,html --reporter-html-export reports/newman.html

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: reports/